# Generated by Django 5.2.5 on 2025-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_variationcategory_options_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'ProductGallery', 'verbose_name_plural': 'product_gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Weight in kilograms (kg)', max_digits=6),
        ),
    ]
