# Generated by Django 5.2.5 on 2025-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_line_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_unit_price',
            field=models.FloatField(default=0),
        ),
    ]
