# Generated by Django 5.2.5 on 2025-09-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
