# Generated by Django 5.2.5 on 2025-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_product_line_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_line_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_unit_price',
            field=models.FloatField(),
        ),
    ]
